### ISSUE TITLE
Make Command Prefixes Optional

### ISSUE THREAD

**Issue by RobertTheSable** [RobertTheSable/sable-text-converter#10]
Fonts in sable can define a command value, which is then prefixed to every command in the font.

It should be possible for specific commands to disable this prefixing.

The syntax should be something like this:
```yml
CommandValue: 0
Commands: 
        End:
            code: 0x00
            prefix: no
        NewLine:
            code: 0x01
            newline: 1
            prefix: no
       SomethingElse:
            code: 0x02
            prefix: yes
```
Prefix should default to "yes" if it's not specified and if CommandValue is defined.

There may be another font setting which controls whether the CommandValue is applied by default. Maybe something like `PrefixCommandsByDefault`?
